field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  9602ed0a-5d19-44a1-9a5b-ca3bfbbdbc7a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83248dab-03cb-497d-bc03-612d85e02528 # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 941b02d6-6200-4d4e-893a-0cdab0a44f83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ddaa2dc-3538-4dac-816d-67ec682d79b8
        userCondition: null
fields:
  83248dab-03cb-497d-bc03-612d85e02528: # Sources
    columnSuffix: krmaseok
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: connectSrc
name: connect-src
sortOrder: 2
