field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  7a9fa511-b408-4b39-bd31-08b216468352:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 62f62c0d-5d72-4158-ae43-c988a4d4a180 # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d750fff-bb06-4b5e-a42d-fb24ebb1ec5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd421b8f-bc8e-4838-a38b-e9c8ed007313
        userCondition: null
fields:
  62f62c0d-5d72-4158-ae43-c988a4d4a180: # Sources
    columnSuffix: etzxxsza
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: defaultSrc
name: default-src
sortOrder: 1
