field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  f3db37db-0e44-41e6-9f75-0530874bb1e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: be5b62b1-1f10-4c40-bcbb-a1505bd9708f # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99be0dc1-ce8d-4a2a-9437-079989f5946d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6cd274f6-29b9-4384-8a03-4cefb5deb2c4
        userCondition: null
fields:
  be5b62b1-1f10-4c40-bcbb-a1505bd9708f: # Sources
    columnSuffix: jsjlvmoe
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: fontSrc
name: font-src
sortOrder: 7
