field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  ddd02140-eeeb-4681-a4ac-f9bdb550df7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91c85d55-934f-4e3c-9e85-5d42c7cad42c # Actions
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42030dfa-efe4-4fe7-9a5a-e07d9457b8ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92d37f49-3ab5-4a14-b4d6-de802114347a
        userCondition: null
fields:
  91c85d55-934f-4e3c-9e85-5d42c7cad42c: # Actions
    columnSuffix: vigmadrj
    contentColumnType: text
    fieldGroup: null
    handle: actions
    instructions: null
    name: Actions
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: formAction
name: form-action
sortOrder: 5
