field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  298b93db-b00c-4285-9902-e16f97ffb5b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cd1d5e4f-4839-4d0a-b222-592fbe90251b # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28906be7-8819-453a-aa06-70a7c5361313
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e3639b7-f549-463f-8d48-6205cd9ba715
        userCondition: null
fields:
  cd1d5e4f-4839-4d0a-b222-592fbe90251b: # Sources
    columnSuffix: wdaoumef
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mediaSrc
name: media-src
sortOrder: 9
