field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  1f964289-b380-4ee5-924d-5196e5fbed0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e248402f-324f-4fc3-b3db-118021402a18 # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfea5700-7069-47a0-92f8-2bf7a59ee6c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3967024a-111d-4219-b8a8-ede11188c9fb
        userCondition: null
fields:
  e248402f-324f-4fc3-b3db-118021402a18: # Sources
    columnSuffix: wgfupsgx
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: objectSrc
name: object-src
sortOrder: 6
