field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  e7c422f2-c262-4f7d-989c-b7f47af91a56:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e5d84a5c-c412-463f-96ae-d8172dc9a07a # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521b5363-d192-4d17-b627-5e2fec16ffaf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a287dd92-bcbb-409a-a34e-382f4a250514
        userCondition: null
fields:
  e5d84a5c-c412-463f-96ae-d8172dc9a07a: # Sources
    columnSuffix: iexjkuoo
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: scriptSrc
name: script-src
sortOrder: 10
