field: c192072a-82d1-40a2-9dc0-71723099dcd0 # CSP
fieldLayouts:
  8d9395fd-26fe-4932-acc4-3a580aa797f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 66d34452-89cc-4bff-b0af-797cf0f491a1 # Sources
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ee5dc9a-cddd-4e8c-80b3-1a6b100c5cbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fb64b2a-57d5-491c-98ee-0ad86492e4e9
        userCondition: null
fields:
  66d34452-89cc-4bff-b0af-797cf0f491a1: # Sources
    columnSuffix: yfepcfsk
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: null
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: styleSrc
name: style-src
sortOrder: 8
