fieldLayouts:
  8b195686-1317-4797-8d9f-8106393d5d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0f3b706-9654-4e91-ad6c-c7a6fde59439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d99d92e-e3cc-44f7-97c6-a034cc21c660 # Max
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c36a0649-61ad-4e1d-9c9d-2ebcb0a9cd3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5499ced-d936-40c2-b045-d0875063944b # Reiner Feld
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5f57872-d221-4d77-aa49-132885ba5094
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8cfffa-f693-418b-bedc-62d6d047943e # Filipa 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c44bdd9-cfcb-4033-a105-598f7648e8e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7689ffd6-2bc9-4ccb-9f0e-705955ea7777 # Felix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e01198ce-221f-4fa3-9256-543762ee2ef4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67ba53aa-2b4a-405b-a95e-c66bd7d8fa3d # Test
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63a13a75-19be-487a-9b9f-50bc2608fa60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82491024-fe0a-4331-a632-7b4e1a03d628 # Konflikt ;)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed9bbc29-08ed-4b45-a43a-a51095449276
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33e4e2e0-ac84-49fd-ad87-186f3ea0666b # Konflikt 2.0 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aab27a7a-6385-497b-9c31-d79be08791f3
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68594230-9efe-49da-80cf-dc0970f98312
        userCondition: null
handle: startseite
hasTitleField: true
name: Startseite
section: 10120e23-43ba-494f-ba6c-7241058df713 # Startseite
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
