color: null
fieldLayouts:
  8b195686-1317-4797-8d9f-8106393d5d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-19T16:36:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0f3b706-9654-4e91-ad6c-c7a6fde59439
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T16:36:19+00:00'
            elementCondition: null
            fieldUid: dffdb509-f1db-4d98-897e-971108a169e2 # CKEditor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 517fd37a-0de4-4675-abfa-d8b72381c3fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T16:36:19+00:00'
            elementCondition: null
            fieldUid: 12994855-fd13-4d38-8ad9-156bb1960e74 # Bilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fef81bc-44ba-4070-967c-51790791d3b6
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68594230-9efe-49da-80cf-dc0970f98312
        userCondition: null
handle: startseite
hasTitleField: true
icon: null
name: Startseite
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
