color: null
fieldLayouts:
  8b195686-1317-4797-8d9f-8106393d5d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-04T17:41:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0f3b706-9654-4e91-ad6c-c7a6fde59439
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-04T17:41:11+00:00'
            elementCondition: null
            fieldUid: 0a064e6b-5fcd-4a2b-acb7-b46630ad5244
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e610b7c-7931-4225-a570-5057ec906e28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-04T17:41:11+00:00'
            elementCondition: null
            fieldUid: 12994855-fd13-4d38-8ad9-156bb1960e74 # Projektbilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fef81bc-44ba-4070-967c-51790791d3b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-06T07:58:37+00:00'
            elementCondition: null
            fieldUid: 352e4f04-b337-41cf-a259-2df2eb9be025
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b824efd1-e9f2-4916-9b35-fc51d38c9020
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68594230-9efe-49da-80cf-dc0970f98312
        userCondition: null
handle: startseite
hasTitleField: true
icon: ''
name: Startseite
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
