fieldLayouts:
  8b195686-1317-4797-8d9f-8106393d5d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0f3b706-9654-4e91-ad6c-c7a6fde59439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8cfffa-f693-418b-bedc-62d6d047943e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c44bdd9-cfcb-4033-a105-598f7648e8e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7689ffd6-2bc9-4ccb-9f0e-705955ea7777
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e01198ce-221f-4fa3-9256-543762ee2ef4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82491024-fe0a-4331-a632-7b4e1a03d628
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed9bbc29-08ed-4b45-a43a-a51095449276
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a064e6b-5fcd-4a2b-acb7-b46630ad5244 # Farbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e610b7c-7931-4225-a570-5057ec906e28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33e4e2e0-ac84-49fd-ad87-186f3ea0666b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aab27a7a-6385-497b-9c31-d79be08791f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12994855-fd13-4d38-8ad9-156bb1960e74 # Projektbilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fef81bc-44ba-4070-967c-51790791d3b6
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68594230-9efe-49da-80cf-dc0970f98312
        userCondition: null
handle: startseite
hasTitleField: true
name: Startseite
section: 10120e23-43ba-494f-ba6c-7241058df713 # Startseite
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
