fieldLayouts:
  8b195686-1317-4797-8d9f-8106393d5d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0f3b706-9654-4e91-ad6c-c7a6fde59439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9dd2aba-1001-4f14-b8a7-ceef123e3743 # Projektbilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2879c5db-c924-4839-81dc-ad8fd2f342c8
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68594230-9efe-49da-80cf-dc0970f98312
        userCondition: null
handle: startseite
hasTitleField: true
name: Startseite
section: 10120e23-43ba-494f-ba6c-7241058df713 # Startseite
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
