columnSuffix: null
contentColumnType: string
fieldGroup: 25d2e79d-a04c-4824-a49f-c3baa6642d8a # Common
handle: bild
instructions: null
name: Bild
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - json
  branchLimit: null
  defaultUploadLocationSource: 'volume:44fec1ae-cc09-42b5-b6a8-1c301d066c04' # Projektbilder
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:44fec1ae-cc09-42b5-b6a8-1c301d066c04' # Projektbilder
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
