columnSuffix: lnhfbfqy
contentColumnType: text
fieldGroup: 25d2e79d-a04c-4824-a49f-c3baa6642d8a # Common
handle: ckeditor
instructions: null
name: CKEditor
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 9e7d0f16-c377-4f3b-a734-ed1f646f1fed # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
