columnSuffix: lnhfbfqy
contentColumnType: text
handle: ckeditor
instructions: null
name: CKEditor
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 9e7d0f16-c377-4f3b-a734-ed1f646f1fed # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
