columnSuffix: null
contentColumnType: string
fieldGroup: 64605225-a1c9-4fc5-8520-475aac61e7c0 # Admin
handle: csp
instructions: null
name: CSP
searchable: false
settings:
  contentTable: '{{%matrixcontent_csp}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
