columnSuffix: uhfsftmw
contentColumnType: boolean
fieldGroup: 64605225-a1c9-4fc5-8520-475aac61e7c0 # Admin
handle: cspAktivieren
instructions: null
name: 'CSP aktivieren'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
