columnSuffix: toxwzikf
contentColumnType: integer(10)
fieldGroup: 25d2e79d-a04c-4824-a49f-c3baa6642d8a # Common
handle: felix
instructions: null
name: Felix
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
