columnSuffix: xvrnkdst
contentColumnType: text
fieldGroup: 25d2e79d-a04c-4824-a49f-c3baa6642d8a # Common
handle: max
instructions: null
name: Max
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
