dateModified: 1726763984
email:
  fromEmail: dev@profitlich.ch
  fromName: 'Profitlich DEV'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  bilder:
    hasUrls: true
    name: Bilder
    settings:
      path: '@assetBasePath/bilder'
    type: craft\fs\Local
    url: '@assetBaseUrl/bilder'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0e793c4c-3298-4c14-a50e-fe050eeaee18: Startseite # Startseite
    9e7d0f16-c377-4f3b-a734-ed1f646f1fed: Simple # Simple
    44fec1ae-cc09-42b5-b6a8-1c301d066c04: Bilder # Bilder
    396abe4e-d4af-4c68-a2fb-7a3bce13f340: Bildbeschreibung # Bildbeschreibung
    10120e23-43ba-494f-ba6c-7241058df713: Startseite # Startseite
    12994855-fd13-4d38-8ad9-156bb1960e74: Bilder # Bilder
    c81f04dd-a4dc-4e6f-a97b-5ce6004b8cf8: 'Profitlich DEV' # Profitlich DEV
    dffdb509-f1db-4d98-897e-971108a169e2: CKEditor # CKEditor
    e814380a-f915-44b8-92b3-a767fa94f64a: 'Profitlich DEV' # Profitlich DEV
plugins:
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  content-security-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cases: true
      maxLength: 160
      minLength: 20
      numbers: true
      showStrengthIndicator: true
      symbols: true
system:
  edition: pro
  live: true
  name: 'Profitlich DEV'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
